name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go mod tidy

      - name: Build the Go binary
        run: GOOS=linux GOARCH=arm64 go build -o bootstrap main.go

      - name: generate zip name
        env:
          ZIP_FILE_TAG: ${{ github.sha }}
        run: |
          echo "ZIP_FILE_NAME=function_$(ZIP_FILE_TAG).zip" >> $GITHUB_ENV
          echo "create file : $ZIP_FILE_NAME"

      - name: Zip the binary
        run: zip $ZIP_FILE_NAME bootstrap

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp $ZIP_FILE_NAME s3://${{ secrets.AWS_MC_DNS_IMAGE_LAMBDA_S3_BUCKET }}

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name mc-dns-image-uploader \
            --s3-bucket ${{ secrets.AWS_MC_DNS_IMAGE_LAMBDA_S3_BUCKET }} \
            --s3-key $ZIP_FILE_NAME
